!!python/object:argparse.Namespace
K: 20.0
arch: resnet18
batch_size: 256
blur: false
ckpt_every_n_epocs: 5
cover_ratio:
- 0.05
- 0.35
crop: false
data: /storage/colinconwell/workspace/deepgaze/Dataset
dataset_name: stl10
device: !!python/object/apply:torch.device
- cuda
disable_blur: true
disable_cuda: false
dry_run: false
epochs: 100
fov_size: 20.0
fp16_precision: false
gpu_index: 0
gridfunc_form: radial_quad
log_every_n_steps: 100
log_root: /storage/colinconwell/workspace/deepgaze/Foveated_Saccade_SimCLR-dev/runs
lr: 0.0003
magnif: true
n_views: 2
out_dim: 256
randomize_seed: true
run_label: test
sal_control: false
sal_sample: false
sample_temperature: 1.5
sampling_bdr: 16
seed: 7855449620729323280
slope_C: 1.5
temperature: 0.07
weight_decay: 0.0001
workers: 16
